src/convert.ts, src/utils/xml.ts
=> handle unicode characters

src/convert.ts, src/resources/summative.ts
Handles converting `activity` elements that point to an summative into a hyperlink to the Torus resource.
=> [FEATURE] Handle summatives embedded within wb pages via activity

src/index.ts, src/resources/create.ts, src/resources/formative.ts, src/resources/questions/cata.ts, src/resources/questions/common.ts, src/resources/questions/multi.ts, src/resources/resource.ts, src/resources/skills.ts, src/utils/resource_mapping.ts
Also adds support for multi input questions that are missing one or more input_refs.
=> [FEATURE] Add support for skills and skill tagging

src/resources/formative.ts, src/resources/questions/cata.ts, src/resources/questions/common.ts, src/resources/questions/rules.ts
Closes https://github.com/Simon-Initiative/oli-torus/issues/2649
This PR improves handling of CATA questions, ensuring that they have a proper "catch all" response.  It also strips out the AUTOGEN responses from echo, but saves one of them to turn it into the catch all.
=> [BUG FIX] Fix cata responses

src/resources/common.ts, src/resources/formative.ts, src/resources/questions/cata.ts, src/resources/questions/multi.ts, src/utils/xml.ts, test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2-pool/complex_ion_pool.xml, test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/entities.xml, test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml
Adjusts dynamic question variable handling, introduces a first gen style question as a test case.
=> [ENHANCMENT] dynamic questions support

src/convert.ts, src/index.ts, src/resources/organization.ts, src/utils/resources.ts, test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/new_page.xml, test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/video.xml, test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/test_org1/organization.xml, test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/test_org2/organization.xml
=> [FEATURE migrate other orgs and products

src/resources/workbook.ts
This PR fixes an issue where citations on a page have no corresponding bib entry. The fix is to simply delete them from the page
=> [BUG-FIX] account for citation tag missing bib entry

src/resources/questions/multi.ts, test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2/newe6ddd6fec8f54749a037ef13abd8df93.xml, test/resources/summative-test.ts
This PR changes numeric input conversions to use the torus numeric equals `=` operator instead of string `like`.
=> [FEATURE] use numeric operator for ranges

src/media.ts, src/resources/common.ts, src/resources/questions/common.ts, src/utils/xml.ts, test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-inline-assessment/command_inline.xml, test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/command.xml, test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/definition_list.xml, test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/mathml.xml, test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml
Detects block-level rendered latex within an inline formula and persists that state in a new `legacyBlockRendered` attribute.
=> [FEATURE] Maintain latex block

src/media.ts, src/resources/organization.ts, test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/test_org1/organization.xml
This PR simply allows organizations custom labels through when parsing organization XML files
=> [FEATURE] Support legacy organization custom labels

src/convert.ts, src/media.ts
This PR reverts a change that broke regular asset identification.
=> [BUG FIX] restore asset handling

src/resources/formative.ts, src/resources/image.ts, src/resources/questions/cata.ts, src/resources/questions/common.ts, src/resources/questions/custom-dnd.ts, src/resources/questions/multi.ts, test/resources/feedback-test.ts, test/resources/summative-test.ts
Fixes an issue where rich content has an unnecessary model property, causing issues when ingested into torus.
=> [BUG FIX] remove model from content in feedback and stems

src/convert.ts, src/index.ts, src/project.ts, src/resources/common.ts, src/resources/feedback.ts, src/resources/formative.ts, src/resources/organization.ts, src/resources/pool.ts, src/resources/resource.ts, src/resources/summative.ts, src/resources/superactivity.ts, src/resources/workbook.ts, src/utils/xml.ts, test/convert-test.ts, test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/alternatives.xml, test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml, test/formative-test.ts, test/old-dtd-test.ts, test/resources/common-test.ts, test/resources/feedback-test.ts, test/resources/questions/common-test.ts, test/resources/summative-test.ts, test/resources/workbook-test.ts, test/utils/xml-test.ts
Adds support for alternatives. The changes here do some rewiring, like removing the default child and bumping the alternative with the default value to be first and tracking all encountered alternatives to store in the _project.json manifest. Part of this was abstracting mediaSummary to be part of a more general projectSummary, where the alternatives and other information is now kept.
=> [FEATURE] Alternatives support

.gitignore, src/index.ts, src/resources/create.ts, src/resources/discussion.ts, src/resources/feedback.ts, src/resources/formative.ts, src/resources/objectives.ts, src/resources/organization.ts, src/resources/questions/cata.ts, src/resources/questions/multi.ts, src/resources/resource.ts, src/resources/summative.ts, src/resources/superactivity.ts, src/resources/workbook.ts, src/utils/dom.ts, src/utils/resources.ts, src/utils/upload.ts, test/resources/workbook-test.ts
Adds Discussion support by converting discussion activities to workbook pages with Collab spaces enabled 
Adds XREF support, converting them to links.
There are a couple of other small bug fixes made here as I worked through conversion of the next round of legacy courses.  Mainly for edge cases like a question part with zero responses, resources that contain a `.` within their id, etc.
=> discussion and xref support

src/resources/questions/custom-dnd.ts
This changes custom drag and drop conversion to avoid the swapping of target and initiator ids to handle MER-1749. DND converted with this version will only work in version of torus incorporating the corresponding torus PR #3279.
Also add a step to clean HTML layouts of any self-closing tags. These occurred in some HTML layouts and were also being generated by conversion of XML layouts. HTML with self-closing tags will not be work correctly in the torus implementation, which sets innerHTML.
=> Custom DND: drop ID swapping MER-1749

src/resources/formative.ts, src/resources/questions/cata.ts, test/resources/summative-test.ts
Shuffle attribute test was incorrect on value of string "false" which is truthy.
=> [BUGFIX] fix handling of shuffle="false" [MER-1970]

src/media.ts, src/resources/common.ts, src/resources/questions/multi.ts, test/course_packages/migration-4sdfykby_v_1_0-echo/content/webcontent/histogram_of_grades.html, test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/histogram1.xml, test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml
Adds webcontent URLS found in iframe src or link href to the set translated to media URLs, w/referenced files included in media manifest for uploading.
=> [BUGFIX] process webcontent URLs in links and iframes [MER-2000]

src/resources/questions/multi.ts, test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2/newe6ddd6fec8f54749a037ef13abd8df93.xml, test/resources/summative-test.ts
Captures the input size attribute for text and numeric multi inputs.
Torus support added in PR https://github.com/Simon-Initiative/oli-torus/pull/3760
=> [ENHANCEMENT] [MER-2165] capture input size attribute for text and numeric

test/content/webcontent/DynaDrop/DynaDropHTML.js, test/content/webcontent/DynaDrop/fdf33e8f7443449492c3b93dcb5df98b_layout.xml, test/content/x-oli-inline-assessment/custom_dnd_4_parts.xml, test/custom-dnd-parts-test.ts
This just adds a test.
While debugging MER-1686, I had written up this simple test that demonstrated why it wasn't working, however recent versions of course-digest work fine, so it passed without any changes.
=> [MER-1686] Added test for 4-part drag drop

test/content/x-oli-inline-assessment/num_sig_fig_digt.xml, test/formative-test.ts
While debugging an issue I created a unit test to verify multi input numeric match values and scores are being converted properly.
=> [ENHANCEMENT] Add a unit test to verify multi input numeric match values and scores

src/index.ts
Removes logging statement leftover from earlier work.
=> remove leftover logging statement

src/utils/xml.ts
L&P includes tables written as mathML formula which used self-closing XML tags for empty table cells, causing errors when rendering in HTML page. This has migration tool rewrite mathML XML to avoid self-closing tags.
=> [ENHANCEMENT] fix mathml to avoid self-closing tags [MER-2975]

src/media.ts
Logic and Proofs include image URLS in mathml table element style attributes. This finds and translates those image references into media library references as for other media references on a page.
=> [ENHANCEMENT] handle image urls in mathml style attributes [MER-2983]

src/resources/questions/multi.ts
Fixes coding errors causing incorrect setting of shuffle option on response_mult questions.
=> [BUGFIX] Fix shuffle setting in response_mult [MER-3032]

src/convert.ts, src/resources/create.ts, src/resources/superactivity.ts
Migration tool was throwing exception on unmigrated activities in composite activities in biochem course due to unmigrated bio_sim superactivities. This (1) migrates the bio_sim activities to generic oli_embed (which may not work, but allows getting through migration); and (2) prevents crash on unmigrated activities in groups.
=> [BUGFIX] [MER-3283] migrate bio_sim; block crash on unmigrated activities in groups

src/resources/superactivity.ts
This PR adds a new scored page per x-cmu-ctattutors. This fixes genetic course package import issue
=> Adds new scored page per x-cmu-ctattutors

src/resources/superactivity.ts
This PR changes the base location where ctattutors bootstrap files are served from
=> Updates x-cmu-ctattutors base folder

src/resources/questions/multi.ts
For math keyboard questions with answers in scientific notation: legacy version of the MathLive keyboard could generate LaTeX of form `4\times 10^3` or `3.2\times 10{-3}` but the newer version used in torus will apparently generate answers of the form`4\times10^3` without a space. This has migration tool remove the space in math input rules containing scientific notation of this form. This is a very special case, but one that is useful for existing physics courses that use math keyboard extensively for scientific notation answers.
=> [MER-3836] [ENHANCMENT] adjust math keyboard latex for scientific notation

src/qti.ts
Questions in the QTI export of pyschology question banks at https://pressbooks.online.ucf.edu/lumenpsychology/chapter/question-banks/ were not being found by the tool, even though the canvas export was in exactly in the QTI version we handle. This was because the manifests in these exports included multiple files per resource, a structure not used in our samples. The questions were in the second file in each resource, which was ignored. This PR adjusts manifest processing to allow for this structure.
Also takes opportunity to put in a small correction which would apply to multiple part dropdown questions, though there were none in our samples.
=> [BUG FIX] [MER-4397] handle QTI resources containing multiple files
