src/convert.ts
src/index.ts
src/resources/formative.ts
src/resources/resource.ts
src/utils/xml.ts

This PR adds support for preserving supporting content blocks within a formative assessment.  Previously these were being dropped on the floor as only the questions themselves were being preserved. 
This PR also makes a change to use the correct inline markup element names for Torus.

[FEATURE] Preserve supporting content in formative assessments

---

src/utils/dom.ts

This PR more correctly handles those elements that use `labelled content`, which can contain both a title and a caption.  Most usages of labelled content use either a label or caption, but this code is able to handle a case where both are present.

[BUG FIX] Handle labelled content

---

src/index.ts
src/resources/webcontent.ts
src/utils/dom.ts

Some of the supporting webcontent files have non-standard references with activities, especially custom activities. Those are currently being ignored by the course-digest. The PR resolves this by appending all other webcontent files to the media-manifest.json

process non-direct referenced webcontent files

---

src/index.ts
src/resources/image.ts
src/resources/superactivity.ts
src/resources/webcontent.ts
src/utils/upload.ts
test/content/x-oli-embed-activity/d9bd71f02ca144bf9246d0631cb2d086.xml

This PR handles the case where multiple files in webcontent folders at various depths within a course package folder end up in the same location at the now flattened webcontent folder structure. The solution is to first sort by file path, then insert a guid into the file path at any subsequent path collision.
Example for the file structure below
package_name
--webcontent
----repl.js
--secondary_level
----webcontent
------repl.js
There resulting flattened webcontent folder would be
webcontent
--repl.js
--457383 (guid)
----repl.js
This PR fixes two other bugs. 
- Torus ingest failing due to expecting the objective object to be a map instead of a list
- Sets mime-type of files uploaded into S3. This allows files such as .css style files to work on browser

ensure flattened file paths deconflict

---

package.json
yarn.lock

This PR removes the "node" dependency from package.json in order to fix an issue installing dependencies using yarn on Mac machines that have M1 processors.

[BUG FIX] remove node dependency for m1 chips

---

src/resources/formative.ts
src/resources/questions/cata.ts
src/resources/questions/common.ts
src/resources/questions/multi.ts
src/resources/summative.ts
src/utils/dom.ts

This PR fixes several issues that were observed during the QA phase of the Pcard and GUSIO courses.
1. https://github.com/Simon-Initiative/oli-torus/issues/2449 - Fixes title handling by converting `<title>` elements of tables and media elements to `<h5>` elements preceding the table or media element.   There is not a problem with the display of paragraphs within tables. The specific example cited in this bug is from a legacy page that contained a table within a list item.  This is not supported in Torus. Tables are top level block elements. 
2. https://github.com/Simon-Initiative/oli-torus/issues/2446 - After generation of a digest and local ingest, images from supporting content seem to be rendering fine now. 
3. https://github.com/Simon-Initiative/oli-torus/issues/2445 - Fixed by …

[BUGFIX] Fixes for missing questions, targeted feedback, title handling

---

src/resources/questions/multi.ts

This PR adjusts how choices are stored for dropdown parts.  We do not want to wrap these in paragraphs like other choices, since ultimately these choices render inside of an HTML `<select>` dropdown and thus need to be simple text. 
Tested against `master` on oli-torus with the pcard course.  I now see the choices rendering correctly for an ingested multi-input dropdown question.

[BUGFIX] Use simple text for dropdown choices

---

src/resources/formative.ts
src/resources/questions/cata.ts
src/resources/workbook.ts
src/utils/dom.ts
src/utils/xml.ts

This fixes https://github.com/Simon-Initiative/oli-torus/issues/2495
Code within Torus was migrating ingested models to V2, since these were not being designated as V2.  This migration (correctly) sets the targeted feedback to an empty list.   By setting the version, we avoid the migration and preserve targeted feedback. 
Also, along with https://github.com/Simon-Initiative/oli-torus/pull/2499, this PR will fix the ability to allow captions with rich text to migrate correctly into Torus. The changes here are to preserve the HTML structure of the `caption` element and store it as the `caption` attribute (which used to simply be a string representation of the caption).

Migration fixes

---

src/resources/common.ts
src/utils/xml.ts
test/resources/common-test.ts

Written to handle nested images in course migrations. the `img_inline` is a new slate element.
https://github.com/Simon-Initiative/oli-torus/issues/2451
https://github.com/Simon-Initiative/oli-torus/issues/2446

Nested images

---

src/convert.ts
src/resources/objectives.ts
src/resources/resource.ts

This PR fixes an issue where the pipe char is an invalid filename character on windows platforms. The fix here is to add the parentId to the Objective resource object and use '-' for concatenations when keying for maps.
Tested on Windows 10 using the following in command prompt:
```
ts-node src/index.ts "--operation" "convert" "--inputDir" ".\\test\\course_packages\\migration-4sdfykby_v_1_0-echo" "--specificOrg" "test\\course_packages\\migration-4sdfykby_v_1_0-echo\\organizations\\default\\organization.xml" "--specificOrgId" "migration-4sdfykby-1.0_default" "--outputDir" ".\\out" "--mediaUrlPrefix" "https://torus-media.s3.amazonaws.com/media"
```

fix an issue where the pipe char is invalid filename character on windows platforms

---

src/convert.ts
src/resources/formative.ts
src/resources/questions/common.ts
src/resources/webcontent.ts
src/resources/workbook.ts
src/utils/debug.ts
test/convert-test.ts
test/resources/questions/common-test.ts

This PR adds support for submit and compare. It also includes the following fixes:
- restore currently file output
- fix an issue where webcontent glob may return a directory
- fix an issue where title was assumed to always be present in example

add support for submit and compare

---

src/resources/workbook.ts

This PR fixes the problem where `<activity>` elements that referenced a summative assessment resulted in the parent practice page having the content and activities of the summative inlined.  The fix here is to simply insert a link to the summative.  
We likely will revisit this approach after reviewing options with the broader team, perhaps by creating an equivalent reference construct in Torus. 
Closes #41

[BUG FIX] handle activity elements

---

src/resources/common.ts
src/utils/common.ts
src/utils/dom.ts
src/utils/xml.ts
test/convert-test.ts
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2/newe6ddd6fec8f54749a037ef13abd8df93.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/extra.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/mathml.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/welcome.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml
test/resources/formula-math-test.ts
test/utils/dom-test.ts

This PR provides support for migrating `<extra>` tag into the Torus popup construct.  
The `extra.xml` file within the embedded test course contains two instances of these elements. I've tested and they ingest correctly. 
This PR also implements support for `<formula>` elements, both inline and block, with proper Torus conversion to handle the three different subtypes: `mathml`, `latex` and `richtext`.    The `richtext` variety gets converted to the new `callout` and `callout_inline` structures within Torus. 
The `mathml.xml` resource demonstrates many different cases that must be supported.  NOTE: one can ingest the generated digest from the embedded test course and render it from Torus, but one cannot edit pages that contain formulas as the Authoring support is still a work in progress. …

[ENHANCEMENT] Add popup, formula and mathml support

---

src/convert.ts
src/media.ts
src/resources/common.ts
src/resources/workbook.ts
src/utils/xml.ts
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-inline-assessment/weak_titration_lbd.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/composite.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/materials.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml

This PR adds support to migrate <materials> element, which is used typically to display two things side-by-side. It migrates materials to a table that is configured to not show it's borders (which Torus doesn't yet support, but will). It handles both orientations that materials DTD element supports: "horizontal" and "vertical")
I found and fixed two other issues:
If a page contained more than one reference to the same image, only one of the references were properly being updated with the new full URL.
Some page content was leading to generation of <td> elements which contained a block element surrounded by two "text" elements that simply contained a single space. This wasn't breaking anything, as once ingested into Torus these spaces turn into paragraphs. But it was adding unnecesary …

[FEATURE] materials and composite_activity element support

---

src/media.ts
src/resources/common.ts
src/utils/xml.ts
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/video.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml

Adds migration support for video elements.  
1. Normalizes "src" attribute from either a single, top-level `src` attr or multiple `<source>` children elements.
2. Sets attribute names for contenttype and url attributes
3. Ensures height and width are numbers

[FEATURE] Add video migration support

---

src/resources/common.ts
src/utils/xml.ts
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/tables.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml

Adds table migration support.  The Torus table model is nearly identical to the legacy model, so there was not much to do here.  I needed to convert `rowspan` and `colspan` attributes to numbers, and adjust the `border` Torus property name.

[FEATURE] Table migration support

---

src/convert.ts
src/resources/skills.ts
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-inline-assessment/newca1a54a0f56a4d429f5aff2c515cab08.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-learning_objectives/dd83841bc84045138faf6f3b7868c6dc.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-skills_model/c04c22b2337f412c8feff2c06e43cef3.xml

This PR fixes a couple of problems related to ingestion of the learning model.
1. LOs attached to pages were not showing up in Torus.  Root cause was that the id of Objective resource was not being set to the "globalized" id.   That was a single line fix (line 138 of `convert.ts`.
2. After fixed 1 above, the objective hierarchy was not being preserved, and attached skills were not being preserved because those attributes still used the "local" id.  Those now get translated to the global id.
Closes #66

[BUG FIX] Properly handle objectives and skill attachments

---

src/resources/formative.ts
src/resources/superactivity.ts
src/utils/dom.ts

Fixes three things for the data science course:
1. Makes the page index determination for branching assessment more robust.  The DS course had page ids in two cases that were unexpected.   The first was of the form: `p3_xxxxx`.  It was assumed previously that page ids were of the form `p3`.    The second case was just a completely bad page id, with no leading `p`.  
2. Sets the `objectives` field for superactivities to be an object with keys of the part ids to empty arrays.
3. Eliminates any resource that appears more than once in the course hierarchy.  The case we will run into a lot with Echo courses is the now infamous `placehodlerid` page.

[BUG FIX] Fixes for data science course

---

src/resources/workbook.ts
src/utils/dom.ts
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/sections.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml
test/resources/workbook-test.ts

Adds support for sections with a purpose set by converting the section into a group with the same purpose and adding the title and content to the group.

[FEATURE] handle sections with purpose attribute

---

src/resources/common.ts
src/resources/formative.ts
src/resources/organization.ts
src/resources/workbook.ts
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/dialog.xml

This PR causes the digest tool fail when it encounters certain blacklisted elements and/or attribute values.  These represent things that the tool and Torus do not yet support.

[ENHANCEMENT] fail for unsupported elements

---

package.json
src/resources/organization.ts
src/resources/workbook.ts
src/utils/xml.ts
src/validate.ts
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/extra.xml
yarn.lock

This PR includes two fixes and two enhancements:
1. Fix: Adjust how the `<labels>` element from organizations was being detected. The initial impl was improperly reporting that an org that didn't include the labels element was using custom labels. 
2. Fix: Ensure that purpose types align with Torus purpose types for `page_link` instances, if not, set it to `none`.
3. Enhancement: Add a utility script to allow validation of all pages.  Usage `npm run validate <the directory to torus schemas>`.  This will validate all pages found in JSON files within the `./out` directory. 
4. Enhancement: Adds support for the `<extra><anchor/><pronunciation/><translation/></extra>` variant of the `<extra>` tag that is used by modern language courses to show a popup with an optional audio clip that …

[ENHANCEMENT] Add validation utility, adjust purpose types, fix label detection

---

src/resources/formative.ts
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2/newc72f87db5a5543b5ae8582d2d4cd34a7.xml

Torus does not support custom feedback for when a student does not answer a question in a summative context.

[ENHANCEMENT] remove no_response

---

src/resources/common.ts
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/media.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml

This change adds an explicit removal of the `width` and `height` attributes for youtube and iframe elements.  Leaving them in place can end up rendering them in Torus, which interfers with the intent to render them in a responsive manner. 
https://eliterate.atlassian.net/browse/MER-1489

[ENHANCEMENT] strip heigh width from responsively rendered media elements

---

src/resources/common.ts
src/resources/questions/multi.ts
src/utils/xml.ts

Sets the new `submitPerPart` field to be `true` for all multiinput questions. 
Also ajdusts the definition list migration for new `<dl>` tagset

[FEATURE] All ingested multiinput use submitPerPart

---

src/utils/xml.ts

Minor adjustment so that `<dl>` elements without titles are processed.

[BUG FIX] handle dl tagset correctly when there are not titles

---

src/resources/common.ts
test/resources/common-test.ts

Similar to `formula`, `image` is a mixed tag in that it can appear inline and as block.  We have to handle detecting when there is an image tag (already renamed here to `img`) that sits at the top level, but whose sibliings are text.  Basically, if this image really needs to be treated as an inline element, then we rename it to `img_line`.  Same solution that we have for `formula`.  
This fixes problems where a stem of a question looks like this:
```
<stem>
Take a look at the image below:
<image src="..."/>
</stem>
```
The first line of the stem gets stripped out if we leave this image as a block image, so we must convert it to inline.
Generate a chemistry course digest and look at the page "Bohr Model of the Atom Calculations", the last inline has two questions.  One of them exhibits the …

[BUG FIX] handle image tags that should be inline image tags

---

src/resources/discussion.ts

This switches the collab space config use of "active" to "enabled" to keep it in lock step with the values that Torus actually uses.

[ENHANCEMENT] change active to enabled

---

src/media.ts
src/resources/superactivity.ts

This PR adds support for CTAT in the course digest tool. It makes use of the existing torus OLI embed custom activity instead of introducing a new custom activity type. 
A CTAT shortcoming that this digest is unable to overcome is how to handle file references within indirect activity support files. Many activities depend on support files such as HTML, CSS, Javascript, brd, etc, that may internally reference other files, usually in a relative fashion. This is particularly problematic given the digest tools file flattening when uploaded into AWS. Extra work will be required to resolve these issues per activity after course import.

Fix ctat import

---

src/resources/questions/common.ts
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-inline-assessment/scientific_notation.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/loosetext.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml

Fix for MER-1744. Changed to preserve non-empty "loose" text pieces found alongside block elements in question stems, as occurs frequently in Chemistry, wrapping them in paragraph tags. Tested by ingesting Chem1 locally and comparing a sample of assessment questions to version on Tokomak. Looks to work without breaking any existing questions.
In one case, seeing the newly ingested text exposed a *different* issue -- subscript tag causes a paragraph break rather than being converted to inline style, badly breaking up CO<sub>2</sub>.  [Update: now corrected]

[BUGFIX] Preserve text alongside block content in stems

---

README.md
src/index.ts
test/convert-test.ts

Minor tweaks for more convenient command line. Primarily for developer use when repeatedly testing:
--inputDir may be abbreviated -i; arg may be relative path.
--outputDir may be abbreviated -o
--operation may be omitted, defaults to convert
--quiet, -q [new option] suppresses prompts and does not zip or upload
Also CHANGES output naming:
outputDir if omitted defaults to ${inputDir}-out
zip file named as ${outputDir}.zip
Together this makes it possible to type simply
`npm run start -- -i courseDir`
to convert a course, leaving courseDir-out and optionally courseDir-out.zip file alongside courseDir in directory tree and
`npm run start -- -qi courseDir`
to convert only without prompting for input.

command line convenience tweaks

---

src/resources/questions/multi.ts

Fixes MER-1745, MER-1746.  Adjusts regex matching for answer patterns for text input items to escape special characters where needed and to support case-insensitive matching where that option is set. 
This also attempts to change the translation of case-_sensitive_ literal string matches into "equals" rules, rather than "like" rules, to avoid escaping metacharacters where not necessary. However, currently the equals operator does not show up on the torus answer authoring interface (MER-1762). These present as "contains" rules on the interface. However, they seem to work as desired.
Case-sensitive matches are rare in the chemistry course, used in only one extra practice on elements. All other text matches in that course are left as case-insensitive.

[BUGFIX] handle special chars in regex match; support case-insensitive matches

---

src/resources/formative.ts
src/resources/questions/common.ts
src/resources/questions/multi.ts
src/utils/xml.ts

For MER-1764, this fixes issue blocking handling of legacy regexps. For unknown reasons, XML processing strips trailing slash from attribute values. Blocked this from applying to "match" attribute. 
Also changed wildcard translation * => .* to apply only to a single * because replacing all *'s in match could interfere with regex.

[BUGFIX] MER-1764 fixes for legacy regexp patterns

---

src/resources/formative.ts
src/resources/questions/common.ts
src/resources/questions/multi.ts
src/utils/xml.ts

This changes the converter output for case-insensitive string answer matches to use the new iequals matching rule, rather than mapping to a regular expression match (which does not do a full string match).  Torus should be updated with #3275 addressing MER-1765 before this version of the digest tool is used.

Use iequals op for case-insensitive string match

---

.vscode/settings.json
src/resources/bibentry.ts

$ is used in some article titles, but the citation-js component we are using to parse citations apparently treats it as a latex math delimiter. Work around this by escaping all $'s in bibliography entry to \$ before handing to the citation-js parser.

MER-1748 escape $ in bib entries for citation-js parser

---

src/resources/formative.ts
src/resources/questions/common.ts

Activity links can occur in question content. Chemistry makes use of this to include references to tables needed to answer the question. This adds steps to find and convert such links. Also improves the wrapping of "loose" text into paragraphs to account for the possibility of inline items like these links.

[BUGFIX]  convert activity links in question stems [MER-1776]

---

src/resources/common.ts

Fix conversion of. audio elements in content by renaming "type" attribute (containing mimeType, e.g. 'audio/mpeg') to "audioType" to avoid conflict with major element "type", which should remain simply 'audio'. Similar to what is done for video elements. Was being done but only for certain specific-context audio elements.

[BUGFIX] Fix conversion of audio elements [MER-1799]

---

src/resources/questions/multi.ts

Fixes conversion of targeted feedback for multi-input questions with dropdown parts. In this case conversion generates new part-qualified IDs for the choices. For example if part1 has choices w/ids A and B, new choice ids are part1-A and part1-B. But this change was not being applied when converting the targeted feedback map, which maps choiceIDs to responses.

[BUGFIX] correct choiceID in multi-input targeted feedback map [MER-1877]

---

src/resources/questions/multi.ts

Multi-input parts were not getting ids in the case where part element has no specified id and also relies on implicit association with inputs by corresponding ordinal position (rather than explicit linking via input attributes on the responses).  French 1 XML uses the implicit association heavily, causing all converted unit quizzes to crash with runtime errors on delivery. Fix generates an id of the form 'partN' where N is the ordinal number of the part in the question in this case. The id is totally arbitrary, but this will be more concise and intelligible than a guid if inspected.

[BUGFIX]Fix case causing multi-input parts w/o ids[MER-1856]

---

src/resources/formative.ts

Correct response's match rule was not being converted correctly on ordering questions. Legacy notation uses comma-separated list of choice ids. This converts them to torus' space-separated form. 
Also allows white space in legacy list because apparently legacy tolerated this (seen in one case).

[BUGFIX] Fix conversion of ordering questions [MER-1801]

---

src/resources/summative.ts

processVariables wasn't being applied to summatives, leading to exceptions converting KTH python2 course.

[BUGFIX] process variables in summatives [MER-1898]

---

src/resources/formative.ts

Within ordering questions only, choices may include a custom color attribute, setting the background color. French uses this to color code choices by speaker in questions asking to order bits of dialog. This has the converter collect custom ordering choice colors and add them to the ordering question model in a new "choiceColors" attribute representing a map from choiceIDs to color namesas an array of [choiceID, colorName] pairs. Intention is for this to be added as an optional element in the torus model, so need not be included where custom colors not used.

[ENHANCEMENT] include color map for custom ordering choice colors [MER-1803]

---

src/resources/formative.ts

Logic and Proofs course evaded the unsupported element check for response_mult because their uses are in pools, and due to bug check wasn't being applied to pools. This is an ad hoc provisional change to address this, but by giving a warning message if it is found. Doesn't quit so work can still be done on other areas of the course. Warning includes question id so can be grepped to tally uses.

Warn on response_mult [MER-1942]

---

src/resources/discussion.ts
src/resources/formative.ts
src/resources/workbook.ts

Adds `<anchor> ` to the list of tags passed to the toJSON parser for which whitespace must be preserved. `<Anchor>` is used for the text within `<extra>` definition translated to popup in torus. Example below. While some semantic elements of this type wrap their content in `<material>`, which was being treated properly, this is not always necessary. Any tag that can contain text content beyond a plain text string must be included, so also included `<translation>`.
```
<extra>
<anchor>Je <em style="emphasis">ne</em> sais <em style="emphasis">plus</em>.</anchor>
<translation>I don’t know anymore.</translation>
</extra>
```

[BUGFIX]  Prevent stripping whitespace within popup anchor text [MER-1797]

---

src/convert.ts

Dangling skillrefs within objectives were leading to nulls in the objectives list, causing problems for torus objectives display observed on KTH ONE-LEARNS migration. This silently filters them from the relevant lists.

Avoid including null objectives for dangling skillrefs

---

src/media.ts

Captivate superactivity can specify a "basepath" asset which should not be treated as a reference to a media file as other assets are. It does reference a webcontent path, but to a directory, causing digest-tool crash on trying to read this as a file for inclusion in media library.

Don't treat basepath asset as media file ref

---

src/resources/questions/common.ts
src/resources/questions/multi.ts

Writes out appropriate per-part shuffle transformations for dropdown parts on multi-inputs, now that torus supports this. Completes fix for torus issue #3470

[BUGFIX] Per-part shuffle transforms for multi-inputs [MER-1987]

---

src/media.ts
src/resources/questions/common.ts
src/resources/questions/multi.ts
test/course_packages/migration-4sdfykby_v_1_0-echo/content/webcontent/html_activities/histogram_of_grades/gh-buttons.css
test/course_packages/migration-4sdfykby_v_1_0-echo/content/webcontent/html_activities/histogram_of_grades/histogram_of_grades.html
test/course_packages/migration-4sdfykby_v_1_0-echo/content/webcontent/html_activities/histogram_of_grades/histogram_of_grades.js
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/histogram1.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml
test/resources/media-test.ts

This attempts to process HTML files loaded as media by finding and adjusting easily-detectable references to local script, css, and image assets. The intent is to handle "html activities" -- framed HTML content made interactive by scripts -- as used in statistics. An example has been added to the migration test course. 
If needed, a modified copy of the file is written into a directory named `<ProjectRoot>-converted` alongside the input directory. This modified copy will be uploaded and used instead of the original. The content-relative tree structure is maintained within this output directory to permit matching up with files in the source and avoid need to rename files. However, only the modified HTML files are written here.
Limits: although intended for content embedded in iframes, the …

[MER-2008] convert refs in framed "HTML Activities" 

---

src/convert.ts
src/index.ts
src/utils/resources.ts
test/convert-test.ts

Fix MER-1899, a hurdle for stats conversion, by making the specificOrg command line parameter actually get used as described. For simpler command line, change to make it take org folder name rather than full path. Org path derived as `${projectDir}/organizations/${specificOrg}/organization.xml `
Allow -g abbreviation for -orG (-o already used for outputDir). Remove never-used specificOrgId parameter.

[BUGFIX] [MER-1899] make specificOrg param work

---

src/resources/common.ts
src/resources/questions/common.ts
src/resources/workbook.ts
src/utils/dom.ts

This takes out the code inlining imgs and stripping paragraphs within list items. It also applies an existing routine to fix up block-containing list items to ensure any loose text items within them get wrapped in paragraphs as required by Slate editor. 
The list item fixup is only applied in workbook pages, which are the only cases we have encountered of block items within list items in Chemistry course. It could be added to other resources if a need arises.

[ENHANCEMENT] Handle blocks within list items [MER-2057]

---

src/media.ts
src/resources/common.ts
src/utils/xml.ts

This adds digest support for outputting 'doublesub' style for double subscripted text and carrying through the 'deemphasis' style for text marked this way in legacy (rendered as normal weight and grey; used in French in some presentations of words with silent letters). Rendering of both of these requires changes on the torus side. 
This also incorporates an unrelated minor fix to trim URLs before checking for relative URLs, needed to get  French content through the digest tool in latest version.

[ENHANCEMENT] doublesub and deemphasis styles [MER-1966]

---

src/resources/common.ts
src/resources/questions/multi.ts
src/utils/dom.ts
test/content/x-oli-assessment2-pool/po7_orbital_dia_UA_pool.xml
test/content/x-oli-workbook_page/p1_changes_enthalpy.xml
test/resources/common-test.ts
test/resources/formula-math-test.ts
test/utils/dom-test.ts
test/utils/step-wrap-test.ts

Fixes https://github.com/Simon-Initiative/oli-torus/issues/3642
To reproduce:
1. Have a <formula> with plaintext in it directly in the body of a document
2. Convert that to torus format
Expected: It gets converted to a callout
Actual: callout_inline
The test for whether the element should be inline or not includes checking for text-nodes as siblings. That test didn't filter out empty text nodes, and returned a false-positive for requiring it to be inline

[Bugfix] Fixed bug causing formulas to import as inline when they could be block

---

.gitignore
src/resources/formative.ts
src/resources/questions/common.ts
test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2/assessment_with_grading.xml
test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml
test/resources/feedback-test.ts
test/resources/summative-test.ts

This PR adjusts the digest tool to pass through the `gradingApproach` attribute in oli_short_answer essay questions part.
Includes a unit test and I tested this end-to-end with the migration course and torus identified the essay oli_short_answer activity as instructor manually graded.
https://eliterate.atlassian.net/browse/MER-2071?filter=10067
Closes [#3537](https://github.com/Simon-Initiative/oli-torus/issues/3537)

[ENHANCEMENT] Pass through grading attribute in oli_short_answer essay questions

---

src/resources/formative.ts
src/resources/workbook.ts
test/content/x-oli-workbook_page/links-test.xml
test/links-test.ts

Torus expects all links to be of {type: 'a'}, previously the digest tool was passing {type: 'xref} which would not display in a torus page correctly. This change converts those `xref` into `a` links, and handles a mismatch in content models. Some rules:
1. An xref with a page attribute will have the resulting `a` link with an idref pointing to that page.
2. An xref with an idref attribute will have the resulting `a` link with an anchor pointing to the idref. Currently, this is ignored in torus, but will be ingested and maintained if the link is edited.
3. An xref without a page attribute, will have it's idref set to the current page. This is an unfortunate case since the link won't do anything until we start supporting the anchor attribute.
In all these cases, the `target` attribute is …

[MER-2072] better handling of xref links

---

src/resources/formative.ts
test/resources/feedback-test.ts

Converts the short_answer inputs from using a text input to a textarea input by default on import.
Before:
After:
As far as I can tell, they're always supposed to be a texarea. I couldn't find a way of specifying it inside echo, and didn't see anything in the DTD to suggest there was an option for different input types. I'm not 100% confident in that conclusion.
Note: the button text is different in torus, so we'll have to edit the lessons to refer to the correct wording.
Fixes https://github.com/Simon-Initiative/oli-torus/issues/3638

[Bugfix] Use textarea instead of text for short answer

---

src/resources/common.ts
src/utils/dom.ts
test/img-caption-test.ts
test/links-test.ts

Image captions have their own slate sub-editor, so the content in those captions must follow the document-level normalization rules we have in place. 
Before, a caption might contain multiple inline elements such as:
`caption: [ {text:"hello"}, {text: "world"} ]`
Now, those will get wrapped up into a paragraph.
`caption: [ {type: 'p', children:[{text:"hello"}, {text: "world"} ]]`
This fixes an issue in chemistry import causing subscript text having extra linebreaks.
Before:
After:
Before:
After:

[MER-2203] Normalizers are causing subscripts to be pushed onto newline

---

src/resources/workbook.ts
test/content/x-oli-workbook_page/double-section.xml
test/section-inline-test.ts

Sometimes, there are wb:inline elements inside a section element, where both the inline and the section specifies a purpose.
In cases where those are the same purpose, we get double headers. We should ignore the purpose on inline elements if they are already inside a section for that purpose.
Before:
After:

[Bugfix] Remove duplicated group headers in output.

---

src/resources/questions/common.ts
src/utils/dom.ts
test/content/x-oli-inline-assessment/feedback-formatting.xml
test/wrap-inlines-test.ts

The reported bug was that there wasn't enough spacing between paragraphs here:
Upon investigation, I found that the content in that feedback consisted of a text node, a paragraph, and a text node. That is not valid slate-js content.  
_Side Note: upon opening it in authoring, the content would get normalized and fixed if the user made any change whatsoever to the page._
The feedback was being passed through `ensureParagraphs` in questions/common.ts which I think was meant to prevent things like this, but `ensureParagraphs` only catches the case where all the children are inline, not when they're partially inline and partially block elements.
In this PR, there is a new `wrapInlinesWithParagraphs` that handles any combination of inline & block elements, wrapping all the inline, and keeping …

[Bugfix] Handle mixed block and inline content in submit & compare feedback

---

src/resources/common.ts
test/content/x-oli-workbook_page/iframes.xml
test/iframes-test.ts

Two changes to support sizing iframes in torus
1. If iframes have an empty <caption /> tag inside them, previously it was expanded to be a caption with a single paragraph in it. Now, it's just removed and no caption is set. This is important because torus will render an extra frame around iframes with captions that throws off the intended alignment/sizing from legacy courses.
2. Iframes where the author has specified a size (ie. it's not the default echo iframe size) will have that size exported. In the case where the iframe is set to 800x450, the default echo size, no size is exported. The thinking is the author didn't set a size and wanted to use the default, and torus has it's own default to use.

[Feature] Maintain iframe width/height

---

src/convert.ts
src/index.ts
src/resources/formative.ts

Tool was not handling legacy wildcard pool selection notation (count="*") used to select every item from a pool and the result in this case was causing crash on use after ingestion. This handles wildcard selection by putting in count of items in the pool. Accomplished by a post-processing step done after all resources have been seen.

[BUGFIX] handle wildcard pool selection[MER-2324]

---

src/resources/common.ts

Migrates theorem elements into a sequence of block-level items representing theorem content.
If no title, legacy theme shows type name as header in slightly smaller style than title. Conversion approximates this behavior to reproduce legacy look, though torus theorem blueprint will not do this. Torus theorem blueprint also includes redundant "Statement" header which legacy never uses.

[ENHANCEMENT] Migrate theorems [MER-1967]

---

src/resources/common.ts

Replicate legacy behavior by inserting "Question" and "Answer" headers before questions and answer blocks within an `<inquiry> `element.

[ENHANCEMENT] insert Question and Answer headers in inquiry element [MER-2220]

---

src/index.ts
src/resources/common.ts

Pullouts can have a "type" field. Possible values include "tosumup" (To Sum Up). The pullout type attribute was not getting renamed, leading to undefined content element errors on ingestion. 
In legacy, the type label is printed in bold followed by ellipses ("To Sum Up...") as a prefix to the pullout content, so this PR implements a version of that.
There are other divergences from legacy pullout behavior that are not addressed: 
-  In legacy, typed pullouts are formatted differently than untyped (untyped render entirely in italics); 
-  legacy merges type label as prefix into first pullout block (title or text content) rather than as header; and 
-   legacy pullouts are indented like block quotes (torus issue [#3659](https://github.com/Simon-Initiative/oli-torus/issues/3659)) -- this is …

[BUGFIX] handle pullout type [MER-2162]

---

src/index.ts
src/utils/upload.ts

If a source filename has characters requiring URL-encoding, such as the combining tilde used in Spanish, migration tool will generate and record a suitable URL-encoded URL for it. For example, `señora.jpg` => `sen%CC%83ora.jpg `where CC 83 is the UTF-8 encoding of the combining tilde.
However, the Amazon S3 API apparently takes a **non**-URL-encoded key which may be any UTF-8 string. (Including special characters may cause trouble for client applications, but is not forbidden in an S3 key).
The upload tool was generating the key from the path part of encoded URL. The result in the above case is that the key includes literal % characters, and the URL-encoded URL needed to access the uploaded file would in fact be `sen%25CC%2583ora.jpg`, using %25 to match the literal percent characters in …

[BUGFIX] upload w/non-Url-encoded S3 key to avoid url mismatches [MER-2514]

---

src/resources/common.ts

Type attribute in video elements was not getting renamed, causing it to be passed through and taken for a content element type on rendering, giving rise to error message ` unsupported content type video/mp4`. Occurs in Logic and Proofs. Apparently never noticed before because type attribute never included in other courses.
One-line fix renames attribute as for audio.

[BUGFIX] rename video type attr as for audio [MER-2560]

---

src/resources/feedback.ts
test/resources/feedback-test.ts

Legacy feedback [survey] description element contains introductory content, generally boilerplate like "Please answer the questions below. Your response will not be graded, but will be available for your instructor to read. Answering these questions may also shape the discussions in class." Migration tool had been deliberately deleting this element, so this content was not being shown. All surveys in chemistry, for example, migrated without this introduction, but apparently no review ever noticed or cared enough about it to report an issue. 
This changes to include description content in the survey. Feedback migration works by converting to the formative representation. The change is just to rename description to "introduction" so it behaves like introduction content in a formative.

[BUGFIX] Include survey description [MER-2594]

---

src/resources/common.ts

Migration tool crashes in certain cases seen in STEM Readiness course where an `extra` element, used for rollover content, is used within side-by-side materials.  This happens when the `extra` element carries the content in the `meaning` sub-element which itself contains a `material` element. The conversion of side-by-side `materials` was reaching into the `material `element nested within the `extra` element when this needs to be left untranslated.
Fix is to limit conversion of `material` within side-by-side `materials` to immediate children.

[BUGFIX] crash on rollover nested within side-by-side materials [MER-2677]

---

src/resources/common.ts
src/resources/create.ts
src/resources/formative.ts
src/resources/pool.ts
src/resources/questions/multi.ts
src/resources/resource.ts
src/resources/summative.ts

Legacy apparently allows an input question, say for a numeric input, to be defined minimally with a purely implied input element with no input id mentioned anywhere: no input element, no input_refs in body, and no input id attribute in part responses. Example from STEM Readiness course:
```
<numeric id="alg_laws_p6_q1">
<body> Expand 6.285 &#8226; 10<sup>3</sup>
</body>
<part>
<response match="6285" score="10">
<feedback>Correct. You moved the decimal point three places to the right.</feedback>
</response>
<response match="*" score="0">
<feedback>Incorrect. Move the decimal point three places to the right.</feedback>
</response>
</part>
</numeric>
```
Migration tool does synthesize implied input elements, but wound up crashing if id not referenced in part response elements. This change …

[BUGFIX] handle implicit input without id [MER-2679]

---

src/resources/create.ts
src/resources/formative.ts
src/resources/pool.ts
src/resources/resource.ts
src/resources/summative.ts

This is a more general and robust solution to MER-2668, needed to handle additional cases like fill-in-the-blank. The fix is to detect and store the pool format (dtd) and suppress summative-to-formative conversion for formative-format pools. 
MEr-2668: Some multiple choice and fill_in_the_blank questions in pools were getting converted into short answer (textarea) questions. Seen in several cases in Logic and Proofs, which is distinctive in using inline assessments that draw from pools.
This happened because (1) questions have different representations in formatives and summatives (in formatives they have no “input” level wrapping choices); (2) pools go through the summative-to-formative conversion; but (3) if the pool uses the formative DTD format, as in the L&P cases, this restructures …

[BUGFIX] some multiple choice questions in pools changed to short answer [MER-2668]

---

src/resources/common.ts
src/utils/xml.ts

This fixes two issues involved with missing popup (legacy `<extra>`) content. First, popup content may be specified in the `<extra>` element content without being wrapped in a semantic subelement like meaning or translation. This case was not being handled.
Second, standard content manipulations to strip bad nested HTML, for example to strip an unordered list within a paragraph, were using selectors that reached down into all descendants. So if a paragraph contained text with an extra (popup) that contained structured content like an unordered list, the nested list level would be stripped because it is contained within a paragraph, leading to incorrect content in the popups. This change revises the selectors to reach only immediate children.

 [BUGFIX] fix lost popup content [MER-2696]

---

src/resources/formative.ts

Legacy OLI allowed multi-part multiple choice questions, unsupported in Torus. Digest tool was converting only the first part. This change converts multipart mcqs to the nearest equivalent in torus, multi-input questions with dropdown parts. This may not be an acceptable presentation of choice content; prints a warning on each instance so these can be identified for careful review.

[ENHANCEMENT] convert multipart mcq to multi-input w/dropdowns [MER-2693]

---

src/resources/common.ts

If a `term` is contained within the content of a `definition` (to highlight some term within that content), it gets migrated into a definition-term, a temporary tool-internal translation which is never eliminated in this case. This causes an “unsupported content element: definition-term” error after ingestion.
This happens because the restructuring code uses a selector "definition term" which reaches into arbitrarily nested descendants, so hits term elements within defnition content when it should not. Fix is to use a selector "`definition>term`" which finds only immediate children.

[BUGFIX] Fix handling of term element within definition content [MER-2706]

---

src/resources/common.ts
src/utils/dom.ts

Legacy OLI permitted lists (ol and ul) to have a title element. Migration tool was not passing these through. This PR turns them into h5 headers prepended to the list, via same routine that processes media titltes.

[BUGFIX] Migrate list titles [MER-2714]

---

src/resources/common.ts

Legacy OLI allowed for conditional inclusion of content based on instructors choice of a course-defined preference setting via the pref:if tag. Use of this gives rise to unsupported content error in migrated content. Since there is no corresponding feature in torus, this change always includes the content to avoid error and allow reviewing instructors to decide how to handle it in torus.

[ENHANCEMENT] include preference conditional content [MER-2715]

---

src/resources/common.ts

Videos with height and width parameters are not being centered in torus. This affected all videos in Logic and Proofs course, which always included intrinsic resolution of video as parameters which ensured display without scaling. This change has the migration tool strip video size parameters to prevent this issue.  Videos will display at a default size, which may then. be scaled from the original resolution.

[BUGFIX] strip video size parameters for centered layout [MER-2727]

---

src/resources/common.ts
src/utils/xml.ts

Legacy highlight style was not being processed. This migrates to torus 'mark' style, which renders as highlight. Note highlight style not yet offered on text styling menu in torus authoring, but apparently implemented.

[BUGFIX] migrate highlight style to mark [MER-2737]

---

src/resources/common.ts

Digest tool was not checking image style attribute (block or inline) before applying its method for inferring whether image should be block or inline. This wound up converting an image explicitly styled as inline into a block image. Change is to give explicit block vs image style priority in deciding.

[BUGFIX] check image style before inferring block or inline [MER-2736]

---

src/utils/xml.ts

Term style was being detected, but missing clause meant it was mapped to strong. Can be mapped to torus term so these show up in green, the style for terms as in legacy.

[BUGFIX] map term inline style to torus term, not strong [MER-2734]

---

src/resources/common.ts

Legacy uses pullouts for content that should be set off from the main flow in some way. Migration was turning these into ordinary paragraphs, losing any indication that they are set off. This change maps pullouts to blockquotes since blockquotes are set off in close to the desired way.
It would seem to be a more natural alternative to migrate to torus callouts. However torus callouts center each line, apparently for the purpose of display formulas written using ordinary text rather than formulas. This is an odd style for pullout content. So, using blockquote as the closest approximation among existing torus content elements.

[BUGFIX] Migrate pullouts  to blockquotes [MER-2733]

---

src/resources/common.ts
src/utils/dom.ts
src/utils/xml.ts

Torus requires a title attribute on a Figure element. Legacy figures did not need to include a title, giving rise to a rendering failure on migrated untitled figures with message "unsupported content element: figure". This change has migration tool  insert an empty title in this case.  Also adds the step of "elevating" content in a figure's child title element in the original XML to a title _attribute_ in the json figure object, which it appears was not being done.
Closes oli-torus:#4405

[BUGFIX] handle untitled figures [MER-2751]

---

src/resources/common.ts

Had example of an image with style=”inline” and a caption. This appeared centered because it was contained within an untitled figure element. This included caption in legacy, but inline images do not show captions in torus.
While this might be addressed by changing source styling to block, this change has migration tool treat all images with captions as block images regardless of style specified, so that the caption will be preserved.

[ENHANCEMENT] never inline captioned images [MER-2769]

---

src/utils/xml.ts

Legacy OLI allowed  `<em style="line-through">` to get strikethrough formatting. This change migrates this to torus strikethrough.
Used in Logic and Proofs, which used a series of non-breaking space characters with line-through styling to get a horizontal line used to separate premises from conclusion in a presentation of an argument. This change is necessary but not sufficient for that to migrate, as there is still a problem passing non-breaking space entities through the migration tool.

[ENHANCEMENT] convert line-through inline style to strikethrough [MER-2781]

---

src/utils/dom.ts
test/utils/dom-test.ts

In addition to captions, legacy OLI allowed titles to be associated with tables/images/iframes/audio/video clips. Torus does not have title elements associated with these. Migration was mapping them to h5 headers, which are not supported as a distinctive element in torus so render in the same way as ordinary text. This PR sets titles on labelled content to display in bold so that they are distinguished from regular text (as in legacy). 
Also changes to use h6 per group discussion so they are distinctive elements unlikely to conflict with section headers even in the future.

[ENHANCEMENT] Give element titles distinctive style [MER-2798]

---

src/convert.ts

Logic and Proofs includes  Unicode nobreak space characters via numerical character reference `&#160;` using sequences of these with strikethrough styling to achieve a horizontal line used to separate premises from conclusion in multiline presentations of an argument structure. These nbsp's were not getting through the migration tool.
These character references should be understood in any XML processor (as should hex` &#xA0;` or simply embedding the unencoded Unicode nbsp character in the UTF8 character stream), but seems cheerio parser has a bug in whitespace normalization so it applies to these nbsp characters, collapsing sequences into a single normal space, at least in XML mode we are using.  (HTML mode with entity decoding might rewrite them to the `&nbsp;` HTML entity reference in …

[BUGFIX] preserve numerically encoded nbsp characters [MER-2834]

---

src/resources/formative.ts
src/resources/questions/common.ts
src/resources/questions/multi.ts

This adds support for translating legacy questions using response_mult into new torus response_multi activities. Legacy response_mult allowed for grouping *sets* of inputs in a multi-input style question and treating those sets as a single part, via response rules that match responses over the set of "target" inputs in that part.

[ENHANCEMENT] convert response mult [MER-2858]

---

src/resources/common.ts

Logic and Proofs courses wrapped many formulas in `<code>` elements for stylistic purposes. While OK if inline, when it results in a block code box, the result in torus doesn't handle this. This PR replaces block code around mathml with p tags.

[ENHANCEMENT] remove block code wrapping  mathml formula [MER-2982]

---

src/resources/formative.ts

Migration tool had been including the correct answer in the targeted feedback list attached to multiple choice questions. While this does not prevent the question from working correctly, it allows the correct answer to be deleted in torus authoring by deleting that targeted feedback, which puts the question in an error state preventing further editing. This corrects migration tool to exclude correct answer from the targeted feedback list.

 [BUGFIX] dont include correct answer in mcq targeted feedback [MER-3033]

---

src/convert.ts
src/resources/questions/multi.ts

Multi-input feedbacks in torus are presented in a list in the order of the parts in the part list. But in some cases, legacy source XML will result in parts for migrated courses coming out in different order than order of inputs in the question stem (it will be order of input section list, to be precise, which may be arbitrary), causing confusion for students matching up feedbacks to inputs. This has migration tool sort parts to ensure parts are listed in order of input items in the question stem.

[BUGFIX] ensure multi-input feedback in order of associated inputs [MER-3039]

---

src/resources/questions/common.ts
src/resources/questions/multi.ts

Torus will always trim whitespace from student input before matching text strings, so an answer match with extraneous white space will be unmatchable. This has the digest tool trim legacy match strings on migrating answer match rules.

[ENHANCEMENT] trim whitespace from text answer match strings [MER-3041]

---

src/resources/pool.ts
src/resources/questions/multi.ts

Migration of section pools now works by merging all questions in the pool into one big multi-input question. Preparing questions for merging involves renaming ids to new, part-qualified ids, including updating the choice Ids used as keys in the targeted feedback mapping. This PR corrects a coding error causing incorrect results when merging more than one multiple choice question with targeted feedback. The code to update the single question-global targeted feedback list needs to occur at the end of the routine, so it operates after all constitutent questions have been processed.
This also fixes targeted feedback listing for multi-input questions to omit the correct answer, same as was done for multiple choice questions.

[BUGFIX] targeted feedback fixes for merged pool sections, multi-inputs [MER-3047]

---

src/resources/questions/multi.ts

Migrate legacy math input questions, identified as text input with attribute keyboard="math", to torus math input type.

[BUGFIX] handle math input questions [MER-3053]

---

src/resources/common.ts
test/resources/formula-math-test.ts

Migration tool had been assuming legacy `<formula>` element would contain a single MathML, LaTex formula. But some legacy courses include mixed content within a formula block. Have seen: 
- two delimited inline LaTeX expressions (the second to add a boxed theorem number); 
- a rich text formula followed by a delimited inline LaTeX formula (again, second to add a boxed number)
- Two MathML expressions linked by plain text " iff ".
This adjusts to only convert legacy formula to torus formula/formula-inline in the case of a single LaTex or MathML expression. Otherwise leaves it as a callout with rich text. Delimited formulas within callout content will be handled by general handling of formulas in rich text content.

[ENHANCEMENT] handle mixed content within formulas [MER-3067]

---

src/resources/common.ts
src/resources/formative.ts
src/utils/dom.ts
src/utils/xml.ts
test/utils/dom-test.ts

Video captions were not being migrated. L&P course uses video captions to include links to transcript pages. 
Because torus videos lack captions, this has migration convert video captions into paragraph content following video element. 
Also renames some caption/title related manipulation routines to be clearer on what they do.

[BUGFIX] migrate video captions [MER-3124]

---

src/resources/create.ts
src/resources/logiclab.ts
src/resources/resource.ts
src/utils/xml.ts

This migrates legacy LogicLab superactivities as used in Logic and Proofs course into torus LogicLab activities. 
In the legacy course, LogicLab descriptors always specify a problem SET of one or more problems from the LogicLab. This migration converts the problem set into a new torus graded page containing references to the individual problems, which are individually converted to torus LogicLab activity resources.

[ENHANCEMENT] Migrate LogicLab activities [MER-3127]

---

src/resources/common.ts

Codeblock lines with trailing whitespace were coming out of migration with extraneous backslashes at the end. This was due to a flaw in the escaping/unescaping of white space done to preserve whitespace through various whitespace-normalizing parses the tool applies. This fixes by escaping leading and internal whitespace only, stripping trailing white space in codeblock lines on assumption it is never needed.

[BUG FIX] [MER-3159] fix extraneous trailing backslash in some code block lines

---

src/resources/common.ts

Migration was not getting syntax highlighting on python codeblocks. Was passing through the legacy language attribute value "python" unchanged.  It seems torus code language ids are the "pretty" capitalized strings displayed in the language choice dropdown menu and lookup is case-sensitive. So in this case language value must be "Python" to work. This converts language values appropriately to get syntax highlighting.
Legacy DTD has only a small number of syntax values defined, so don't have to worry about mapping "sql" => "SQL" or "typescript" => "TypeScript", but do have to map "cpp" => "C++".

[BUGFIX] [MER-3226] map code language values to torus versions for syntax coloring

---

src/resources/questions/multi.ts
src/resources/workbook.ts

Post-test in one course was not loading because link in source workbook page did not have a purpose, and torus requires a purpose to render the link. This corrects logic to ensure page links always have a purpose, filling in "none" in the case where source has none specified.

[BUGFIX] [MER-3232] Ensure page_links have purpose value

---

src/resources/questions/multi.ts

Migration tool normally sets the submitPerPart option on multi-inputs. With this option, question omits a Submit button, automatically submitting any non-empty answer contents on Enter key or loss of focus. But activating math input keyboard apparently interferes with torus' handling these events, leaving no way to submit answer when this option is used. So, don't set it if question includes any math input items.

[BUGFIX] [MER-3228] Don't set submitPerPart if q has math input part

---

src/utils/xml.ts

Legacy allowed "emphasis" inline style, tool was not handling this.

[BUGFIX] [MER-3248] handle emphasis style

---

src/resources/questions/common.ts

Legacy allowed questions with no correct answer or feedback. Some of these cause a crash in migration tool, others lead to migrated questions that can't be authored due to invalid no correct answer error state (seen in Italian course on submit and compare type questions). This improves the handling of these questions by printing a warning but synthesizing a wildcard correct response if needed, so migration can proceed.

[ENHANCEMENT] [MER-3254] handle missing responses on text input questions

---

src/resources/create.ts
src/resources/superactivity.ts

Fixes two errors in the attempt at bio_sim superactivity support:
1. fixes coding error in testing resource type introduced with bio_sim case.  Led to error on handling a few little-used resource types, including any unknown types like print_cert.
2. corrects base filled in for bio_sim superactivity.

[BUG FIX] [MER-3319] [MER-3289] Uningestible output for print_cert resource

---

src/resources/common.ts
src/utils/dom.ts
test/convert-test.ts
test/resources/workbook-test.ts
test/utils/dom-test.ts

Title elements on alternatives were not being migrated, causing errors (seen in Alvin Statistics). This PR processes titles included on alternatives. 
Also, title elements on some other elements, prominently examples, were being converted to ordinary paragraphs so they rendered with no distinctive styling [MER-3384] This PR changes to use a common routine for titles on all these elements to ensure synthesized titles are consistently rendered in a distinctive bold style.
This also improves Inquiry formatting [MER-3386] by using same method to style title distinctively, adding "INQUIRY: " prefix, and, in an independently requested tweak, changing to use same size for Question and Answer headers.
[MER-3384]: https://eliterate.atlassian.net/browse/MER-3384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

[BUG FIX] [MER-3383] [MER-3384] [MER-3386] Handle titles of alternatives, examples, inquiry

---

src/resources/common.ts
src/utils/dom.ts

Alvin statistics course contains alternatives within pullouts to conform to a convention that statistical package instructions are rendered as pullouts. This won't work in torus since pullouts and alternatives are block elements. In addition the alternative content itself is generally complex, with multiple paragraphs and/or bulleted lists. 
This simple solution just eliminates the pullout level if it contains alternatives. This suffices to get the content legibly rendered.

[ENHANCEMENT] [MER-3389] Handle pullouts containing alternatives

---

src/resources/formative.ts
src/resources/questions/common.ts

This adds flags used by torus authoring to show the Custom score authoring interface for questions with non-default point values. Failure to do this meant the authoring did not show the true point values being passed through, leading to problems. However, this change is no longer so urgent since torus authoring was changed to recognize "implicit" custom scoring indicated only by the presence of non-default point values (see https://github.com/Simon-Initiative/oli-torus/pull/4877). However it can only help prevent errors to include the explicit settings used by the newer Custom-score-handling code.

[ENHANCEMENT] [MER-3395] set custom scoring flags on activity models where needed

---

src/resources/questions/cata.ts
src/resources/questions/common.ts

Legacy submit and compares were being approximated by torus text input questions in which every answer was correct, but this allows blank submissions to get the answer feedback to compare.  In response to requests from LEs, this adjusts the torus output for a legacy submit and compare question to use a regular expression rule to ensure that blank submission is not accepted as correct. With this adjustment, blank submissions will get incorrect (red) colored feedback "Please enter a response".  
The regex .+ works for detecting non-blank answers because torus trims whitespace before evaluating. This crude method still allows a nonsensical or one-character entry. But at least prompts students not to simply hit "submit" on an empty text box and more closely matches legacy submit and compare …

[ENHANCEMENT] [MER-3400] adjust submit and compare to require non-blank input

---

src/resources/common.ts
src/resources/questions/common.ts

This removes alternatives structure where it occurs in feedback or explanations (used for submit and compare) because that doesn't work in torus. The effect is that all alternatives are included, preceded by their title if present. (Alternative titles are included in the statistics courses giving rise to this issue). The migrated feedback may well need to be reviewed and edited, but it gets through migration into an acceptable structure. 
This also takes the opportunity to relocate the adjusting of submit and compare to handle the case of questions with no responses, which arose in the Alvin statistics course motivating the current enhancement.

[ENHANCEMENT] [MER-3424] strip alternative level from feedback

---

src/media.ts
src/resources/superactivity.ts

Some CTAT superactivities of type` x-cmu-ctattutors` used in Genetics course have an `<interface>` element referencing a "sequence.xml" file defining a _set_ of problems, rather than an HTML file to be loaded. The use of sequence files cause problems for migrating these superactivities because the sequence files contain asset references that must be translated for use in torus. But these files are not resource files we would otherwise process in any way, rather just webcontent files.
Here we detect this case and handle by constructing a torus variant sequence file with translated URLs and adding it to the webcontent tree, adjusting the sequence file reference in the original superactivity descriptor to point to the torus variant. Because the CTAT superactivity code detects sequence file …

[ENHANCEMENT] [MER-3615] handle CTAT tutors using sequence files (Genetics)

---

src/resources/formative.ts
src/resources/questions/common.ts
src/resources/questions/multi.ts

French course included some manually graded multi-input questions with text inputs. These were not being migrated correctly, not only because the grading type attribute was not processed at all for this question type, but also because questions used part definitions of the following form:
```
<part id="part1" targets="M2L1_pool2_q3_input1" score_out_of="3" />
<part id="part2" targets="M2L1_pool2_q3_input2" score_out_of="4" />
<part id="part3" targets="M2L1_pool2_q3_input3" score_out_of="3" />
```
in which parts are associated with inputRefs vis the "targets" attribute and contain no responses, a structure that also was never handled.
This PR adds support for migrating such questions correctly. It fills in default correct and incorrect responses to get past torus authoring UI requirements. …

[BUG FIX] [MER-3636] handle manual graded multi-inputs

---

package.json
src/resources/bibentry.ts
yarn.lock

Author fields in legacy bibliography entries were getting parsed as proper names in the conversion pipeline, leading to institution authors like "Dept of Labor" being rendered "of Labor, D." in migrated reference lists. It turns out legacy theme always rendered the author field contents literally without change. This allows for institutions as authors, but requires legacy content author to enter author field contents in proper bibliography form if needed. This PR takes steps to ensure author contents pass through migration literally. 
This PR also takes the opportunity to upgrade to the latest version of the citation-js module, used to manage conversion by the digest tool and rendering of bibliography entries by torus client-side components. That suffices to fix MER-3802,  bib:misc type …

[BUG FIX] [MER-3802] [MER-3803] Ensure bibliography author field migrates as is

---

src/resources/formative.ts
src/resources/workbook.ts

This migrates instructor-only content blocks on summative assessments and workbook pages. These are used extensively on quiz pages in CAHIMS course to include an instructor-only block giving link to the quiz solution. Processing also included for workbook pages because it is easy enough to support, though we have not encountered this case in a course.

[MER-3967] [ENHANCEMENT] Migrate instructor-only content blocks

---

src/resources/common.ts

Composite activity containing a paged lbd in psychology course was causing problems for migration due to extra level of group nesting this gives rise to. However, turns out this was due to an entirely unnecessary use of the composite_activity tag to contain a single activity, evidently a style used by these course authors. Rather than rewrite source, this has migration tool strip redundant composite_activity tags wrapping a single child.

[MER-3973] [BUG FIX] strip composite activity w/only one child

---

src/resources/common.ts

Torus figure elements have a title, but no caption. Legacy OLI figures may have both; this case was not being handled correctly. This PR handles figures with captions by migrating as plain images, w/any title prepended before it, just as if it was a titled image (which was also allowed in legacy).

[MER-3972] [BUG FIX] handle figures with captions

---

src/resources/common.ts

Anatomy & Physiology makes frequent use of side-by-side materials structure containing an image on one side and an inline assessment with one or more questions about the image on the other. While side-by-side materials can be migrated into torus tables, activities cannot be contained inside tables. This PR eliminates the side-by-side structure in this case so the course can be migrated into a structure the authors can see and perhaps edit. This will result in a sequential layout with the image above the questions.

[ENHANCEMENT] [MER-4000] strip side-by-side materials containing activities

---

src/media.ts

The ctat `statttutor` superactivity script used in Alvin Statistics course relies on a URL query parameter on its base html page in order to find information about the specific problem, using a hard-coded internal table for this. The path translation being done by the migration tool was not preserving query parameters (on assumption they were simply file refs), causing the migrated problems to fail to initialize. This change carries through any query parameter on these asset paths.
This PR includes some miscellaneous changes make the superactivity asset element path translation a bit more robust and simplify the code.

[BUG FIX] [MER-4092] preserve query param in superactivity asset refs

---

src/index.ts
src/resources/organization.ts

Legacy organization items may include a `<description> `element containing descriptive text about the item. Passing these through for any item other than the root causes an error on ingestion as torus does not have a counterpart on its containers and ingestion is not coded to handle them This just removes any description elements on containers before further processing of the organization.
This PR also takes the opportunity to put in a more helpful error message for the case of a bad input directory on the command line.

[BUG FIX] [MER-4115] strip description elements from organization container items

---

src/resources/formative.ts
src/resources/questions/cata.ts
src/resources/questions/common.ts
src/resources/questions/multi.ts

This fixes migration tool to fill in targeted feedback map for ordering questions. Failure to do this was the cause of https://eliterate.atlassian.net/browse/MER-4142. Also has it strip Echo "AUTOGEN" responses (set automatically generated identical responses for all possible wrong answers without substantive feedback) on these questions as is done for legacy CATA questions. This turned up typo and error breaking autogen processing even for CATA, so fixes that  as well.

[BUG FIX] [MER-4149] handle ordering targeted feedback

---

README.md
package.json
src/convert.ts
src/index.ts
src/project.ts
src/qti.ts
src/resources/common.ts
src/resources/questions/common.ts
src/resources/questions/multi.ts
src/utils/common.ts
test/qti-convert-test.ts
test/qti/Mod2ReadingQuiz/g3e9bef852d702d51e2f7d73269ed2023/assessment_meta.xml
test/qti/Mod2ReadingQuiz/g3e9bef852d702d51e2f7d73269ed2023/g3e9bef852d702d51e2f7d73269ed2023.xml
test/qti/Mod2ReadingQuiz/imsmanifest.xml
test/remove-reundundant-input-test.ts
yarn.lock

This adds a mode of the migration tool to convert QTI format exports of questions. It is invoked by operation argument `qti` and otherwise takes same parameters as the `convert `operation.
` npm start -- qti -i inputDir`
`inputDir` should be path to a folder containing one or more QTI packages in .zip format (must have this extension). Note spaces required on both sides of the double-hyphen which serves as a separator. 
This will add all convertible questions into an ingestible archive as activity bank items. Question types handled are Multiple Choice, Check All That Apply, Dropdown items (maybe multiple), Short Answer numeric, and Short Answer numeric with dynamic variables (corresponding to Canvas "calculated" question types). All items receive default scoring. Questions are tagged with …

[ENHANCEMENT][MER-4356] convert QTI exported quiz questions

---

src/convert.ts
src/index.ts
src/resources/formative.ts
src/utils/common.ts

Some activities in migrated Concepts of Statistics course wound up missing their learning objectives. 
Found this happening on fill in the blank questions on which the XML listed the skillrefs _outside_ of a part. Migration tool expects the skillrefs to be _inside_ the part because each part in a multi-part question may involve different skills. The cases where this was found were in fact single part dropdown questions, so it is not semantically necessary in this case, and perhaps legacy allowed this. Fix is to adjust migration tool to allow for this.
While investigating this issue, also identified a subtle coding issue which caused all but the first item in the inventoried list of x-oli-learning_objectives + x-oli-skills_model resources to be processed twice. This stemmed from an …

[BUG FIX] [MER-4427] fix missing learning objectives in some courses

---

src/resources/questions/cata.ts
src/resources/questions/common.ts

Migrated CATA questions were not getting the proper catchAll incorrect feedback. This was due to a bug in the handling of Echo autogenerated responses, which does attempt to replace the large set of autogenerated responses with a single catchAll, preserving the specified feedback. 
The bug was due to a subtlety introduced into the processing of cata questions at some point, so that it occurs in two stages: an initial stage at which the "rule" field of the response provisionally stores the legacy match pattern, and a later stage that translates all response rules into torus rules. The autogen conversion occurred in stage one, but the result was not in the form of the initial stage so wound up unrecognized as the catchall by the later processing, leading to the tool filling in a catchall …

[BUG FIX] [MER-4804] Preserve catchAll feedback on CATA questions

---

src/convert.ts
src/utils/spreadsheet.ts

Legacy courses could have a skills model specified in an external spreadsheet, sometimes referred to as a “Magic Spreadsheet”. The migration tool can optionally process these to attach Learning Objectives to resources in the course. 
However, the french1 spreadsheet uses certain coding conventions for identifying items in pools that the migration script does not process, identifying a problem by compound ids of the form `poolID_qId`, where qId is actually a suffix like q1, q2, q3 on the full id.  It also uses these conventions also for some assessment items, though it should not be necessary in the case of assessment questions. 
Additionally, migration script requires an LO Refs sheet, giving up processing if it is not found, but in fact this can be omitted and everything will still work …

[ENHANCEMENT] [MER-4991] handle conventions in french1 skills spreadsheet
